// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Models.ORM.Context;

namespace Restaurant.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210323175240_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Restaurant.Areas.Admin.Models.Entities.RestaurantDetail", b =>
                {
                    b.Property<int>("RestaurantDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anayemek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<string>("Meze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salatalar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tatlılar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İçecek")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantDetailId");

                    b.ToTable("restaurantDetails");
                });

            modelBuilder.Entity("Restaurant.Models.ORM.Entities.RestaurantBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantMenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("restaurantBases");
                });
#pragma warning restore 612, 618
        }
    }
}
